Repository exercism/discord-bot-py, pull requests merged in 2023-07, with the labels that each got.

#28 Add message for complete beginners
  conf.py
Labels: x:size/small, x:type/docs, x:rep/small

#65 Beginner msg - Fix stray space
  conf.py
Labels: x:type/docs, x:size/tiny, x:rep/tiny

#66 TrackReact: change thread log item from INFO to DEBUG
  cogs/track_react.py
Labels: x:size/tiny, x:rep/tiny

#67 ModMessage: log which message was triggered
  cogs/mod_message.py
Labels: x:size/tiny, x:rep/tiny

#68 RequestNotifier: Add timeone when fetching a thread
  cogs/mentor_requests.py
Labels: x:size/small, x:rep/small
